apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment2
spec:
  selector:
    matchLabels:
      name: my-app2
  template:
    metadata:
      labels:
        name: my-app2
    spec:
      containers:
        - name: rapstartupgo
          image: rakaadli/rapstartupgo
          env:
            - name: PORT
              value: "8080"