apiVersion: v1
kind: Pod
metadata:
  name: my-pod1
spec:
  containers:
    - name: hello-raka
      image: adamstudiodocker/udemy-praktis-belajar-docker-dan-kubernetes-untuk-pemula:hello-world
      env:
        - name: PORT
          value: "8080"